# Generated by Django 5.0.2 on 2025-07-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('merek', models.CharField(max_length=100)),
                ('tahun', models.PositiveIntegerField()),
                ('jumlah_kursi', models.PositiveIntegerField()),
                ('transmisi', models.CharField(max_length=50)),
                ('harga_per_hari', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tersedia', models.BooleanField(default=True)),
            ],
        ),
    ]
