# Generated by Django 5.0.2 on 2025-07-03 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_penyewaan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobil',
            old_name='harga_per_hari',
            new_name='harga_sewa',
        ),
        migrations.RemoveField(
            model_name='mobil',
            name='jumlah_kursi',
        ),
        migrations.RemoveField(
            model_name='mobil',
            name='transmisi',
        ),
        migrations.CreateModel(
            name='RiwayatPenyewaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelanggan', models.CharField(max_length=100)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('mobil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.mobil')),
            ],
        ),
        migrations.DeleteModel(
            name='Penyewaan',
        ),
    ]
