# Generated by Django 5.0.2 on 2025-07-03 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_rename_harga_per_hari_mobil_harga_sewa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobil',
            old_name='merek',
            new_name='merk',
        ),
        migrations.RenameField(
            model_name='riwayatpenyewaan',
            old_name='nama_pelanggan',
            new_name='nama_penyewa',
        ),
        migrations.AddField(
            model_name='mobil',
            name='plat_nomor',
            field=models.CharField(default='TIDAK-DIKETAHUI', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riwayatpenyewaan',
            name='total_harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobil',
            name='tahun',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Penyewaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penyewa', models.CharField(max_length=100)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mobil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.mobil')),
            ],
        ),
    ]
