# Generated by Django 5.0.2 on 2025-07-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_rename_merek_mobil_merk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobil',
            name='harga_sewa',
        ),
        migrations.AddField(
            model_name='mobil',
            name='harga_per_hari',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='mobil',
            name='jumlah_kursi',
            field=models.IntegerField(default=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobil',
            name='transmisi',
            field=models.CharField(default=100000, max_length=50),
            preserve_default=False,
        ),
    ]
