# Generated by Django 5.2.4 on 2025-07-20 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobil',
            options={'verbose_name': 'Mobil', 'verbose_name_plural': 'Daftar Mobil'},
        ),
        migrations.AlterModelOptions(
            name='penyewaan',
            options={'verbose_name': 'Penyewaan', 'verbose_name_plural': 'Daftar Penyewaan'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profil Pengguna', 'verbose_name_plural': 'Daftar Profil Pengguna'},
        ),
        migrations.AlterModelOptions(
            name='riwayatpenyewaan',
            options={'verbose_name': 'Riwayat Penyewaan', 'verbose_name_plural': 'Daftar Riwayat Penyewaan'},
        ),
        migrations.AlterField(
            model_name='mobil',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='mobil/', verbose_name='Gambar Mobil'),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='harga_per_hari',
            field=models.IntegerField(default=100000, verbose_name='Harga per Hari'),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='jumlah_kursi',
            field=models.IntegerField(verbose_name='Jumlah Kursi'),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='merk',
            field=models.CharField(max_length=100, verbose_name='Merk'),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='nama',
            field=models.CharField(max_length=100, verbose_name='Nama Mobil'),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='plat_nomor',
            field=models.CharField(max_length=20, verbose_name='Plat Nomor'),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='tahun',
            field=models.IntegerField(verbose_name='Tahun Produksi'),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='tersedia',
            field=models.BooleanField(default=True, verbose_name='Tersedia'),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='transmisi',
            field=models.CharField(max_length=50, verbose_name='Jenis Transmisi'),
        ),
        migrations.AlterField(
            model_name='penyewaan',
            name='mobil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.mobil', verbose_name='Mobil'),
        ),
        migrations.AlterField(
            model_name='penyewaan',
            name='nama_penyewa',
            field=models.CharField(max_length=100, verbose_name='Nama Penyewa'),
        ),
        migrations.AlterField(
            model_name='penyewaan',
            name='tanggal_mulai',
            field=models.DateField(verbose_name='Tanggal Mulai'),
        ),
        migrations.AlterField(
            model_name='penyewaan',
            name='tanggal_selesai',
            field=models.DateField(verbose_name='Tanggal Selesai'),
        ),
        migrations.AlterField(
            model_name='penyewaan',
            name='total_harga',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Harga'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Foto Profil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pengguna'),
        ),
        migrations.AlterField(
            model_name='riwayatpenyewaan',
            name='mobil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.mobil', verbose_name='Mobil'),
        ),
        migrations.AlterField(
            model_name='riwayatpenyewaan',
            name='nama_penyewa',
            field=models.CharField(max_length=100, verbose_name='Nama Penyewa'),
        ),
        migrations.AlterField(
            model_name='riwayatpenyewaan',
            name='tanggal_mulai',
            field=models.DateField(verbose_name='Tanggal Mulai'),
        ),
        migrations.AlterField(
            model_name='riwayatpenyewaan',
            name='tanggal_selesai',
            field=models.DateField(verbose_name='Tanggal Selesai'),
        ),
        migrations.AlterField(
            model_name='riwayatpenyewaan',
            name='total_harga',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Harga'),
        ),
    ]
